-- A natural conversation with 200 messages between two developers discussing various tech topics. The conversation includes:

-- Realistic flow: Messages have varied timing, from quick back-and-forth to longer pauses
-- Natural topics: Debugging, programming languages, frameworks, tools, work life, ergonomics
-- Casual tone: Includes "lol", emojis, incomplete thoughts - just like real chat
-- Generic structure: Uses variables (room_id, user1_id, user2_id) that you can easily replace

-- To use it:

-- Replace room_id with your actual room UUID
-- Replace user1_id with the first user's UUID
-- Replace user2_id with the second user's UUID

-- The timestamps start 3 hours ago and spread across ~2.5 hours of conversation time with realistic breaks, making it feel authentic!


DO $$
DECLARE
    base_time TIMESTAMPTZ := NOW() - INTERVAL '3 hours';
    room_id UUID := 'b540e65f-84b7-42f6-8a56-b3609a65137a';
    user1_id UUID := 'c0115a60-66c8-4c2e-9312-c90df68d5316';
    user2_id UUID := '566b2b9a-8a73-4211-ab89-8195b01857e5';
BEGIN
    -- User1 starts the conversation
    INSERT INTO messages (room_id, user_id, content, created_at) VALUES
    (room_id, user1_id, 'hey everyone! anyone around?', base_time),
    (room_id, user2_id, 'yo! what''s up?', base_time + INTERVAL '2 minutes'),
    (room_id, user1_id, 'not much, just finished a brutal debugging session', base_time + INTERVAL '3 minutes'),
    (room_id, user2_id, 'oh no, what was the issue?', base_time + INTERVAL '3 minutes 30 seconds'),
    (room_id, user1_id, 'race condition in our websocket implementation', base_time + INTERVAL '4 minutes'),
    (room_id, user1_id, 'took me 3 hours to figure out', base_time + INTERVAL '4 minutes 15 seconds'),
    (room_id, user2_id, 'ouch, those are the worst', base_time + INTERVAL '5 minutes'),
    (room_id, user2_id, 'did you manage to fix it?', base_time + INTERVAL '5 minutes 20 seconds'),
    (room_id, user1_id, 'yeah, had to add proper mutex locks', base_time + INTERVAL '6 minutes'),
    (room_id, user1_id, 'feeling pretty accomplished now though lol', base_time + INTERVAL '6 minutes 30 seconds'),
    (room_id, user2_id, 'nice! nothing beats that feeling', base_time + INTERVAL '7 minutes'),
    (room_id, user2_id, 'what language are you working in?', base_time + INTERVAL '7 minutes 45 seconds'),
    (room_id, user1_id, 'Go, for our backend services', base_time + INTERVAL '8 minutes'),
    (room_id, user2_id, 'oh cool, I''ve been wanting to learn Go', base_time + INTERVAL '8 minutes 30 seconds'),
    (room_id, user2_id, 'how do you like it?', base_time + INTERVAL '8 minutes 45 seconds'),
    (room_id, user1_id, 'honestly? I love it', base_time + INTERVAL '9 minutes'),
    (room_id, user1_id, 'the concurrency model is chef''s kiss', base_time + INTERVAL '9 minutes 20 seconds'),
    (room_id, user1_id, 'goroutines and channels make concurrent programming so much easier', base_time + INTERVAL '10 minutes'),
    (room_id, user2_id, 'that''s what I keep hearing', base_time + INTERVAL '10 minutes 30 seconds'),
    (room_id, user2_id, 'I''m still mostly doing Python and JavaScript', base_time + INTERVAL '11 minutes'),
    (room_id, user1_id, 'nothing wrong with that! what kind of projects?', base_time + INTERVAL '11 minutes 45 seconds'),
    (room_id, user2_id, 'web apps mostly, some data analysis stuff', base_time + INTERVAL '12 minutes'),
    (room_id, user2_id, 'working on a React project right now', base_time + INTERVAL '12 minutes 30 seconds'),
    (room_id, user1_id, 'nice, React is solid', base_time + INTERVAL '13 minutes'),
    (room_id, user1_id, 'have you tried Next.js?', base_time + INTERVAL '13 minutes 20 seconds'),
    (room_id, user2_id, 'yeah actually! that''s what I''m using', base_time + INTERVAL '14 minutes'),
    (room_id, user2_id, 'the App Router is still confusing me a bit though', base_time + INTERVAL '14 minutes 30 seconds'),
    (room_id, user1_id, 'haha yeah the learning curve is real', base_time + INTERVAL '15 minutes'),
    (room_id, user1_id, 'but once it clicks, it''s pretty powerful', base_time + INTERVAL '15 minutes 30 seconds'),
    (room_id, user2_id, 'that''s what I''m hoping for', base_time + INTERVAL '16 minutes'),
    (room_id, user2_id, 'btw, what do you use for state management?', base_time + INTERVAL '16 minutes 45 seconds'),
    (room_id, user1_id, 'depends on the project honestly', base_time + INTERVAL '17 minutes'),
    (room_id, user1_id, 'for simple stuff, just React hooks', base_time + INTERVAL '17 minutes 30 seconds'),
    (room_id, user1_id, 'for complex apps, Zustand or Jotai', base_time + INTERVAL '18 minutes'),
    (room_id, user2_id, 'never used Jotai, is it good?', base_time + INTERVAL '18 minutes 30 seconds'),
    (room_id, user1_id, 'I really like it! super minimal', base_time + INTERVAL '19 minutes'),
    (room_id, user1_id, 'less boilerplate than Redux', base_time + INTERVAL '19 minutes 30 seconds'),
    (room_id, user2_id, 'ugh Redux...', base_time + INTERVAL '20 minutes'),
    (room_id, user2_id, 'I spent way too much time setting that up on my last project', base_time + INTERVAL '20 minutes 30 seconds'),
    (room_id, user1_id, 'lol I feel you', base_time + INTERVAL '21 minutes'),
    (room_id, user1_id, 'Redux has its place but it can be overkill', base_time + INTERVAL '21 minutes 30 seconds'),
    (room_id, user2_id, 'exactly', base_time + INTERVAL '22 minutes'),
    (room_id, user2_id, 'so what are you working on these days?', base_time + INTERVAL '22 minutes 45 seconds'),
    (room_id, user1_id, 'building out a real-time collaboration platform', base_time + INTERVAL '23 minutes'),
    (room_id, user1_id, 'think Google Docs but for data visualization', base_time + INTERVAL '23 minutes 30 seconds'),
    (room_id, user2_id, 'whoa that sounds ambitious', base_time + INTERVAL '24 minutes'),
    (room_id, user2_id, 'and complicated', base_time + INTERVAL '24 minutes 15 seconds'),
    (room_id, user1_id, 'oh it definitely is', base_time + INTERVAL '25 minutes'),
    (room_id, user1_id, 'hence the websocket debugging earlier lol', base_time + INTERVAL '25 minutes 30 seconds'),
    (room_id, user2_id, 'haha makes sense', base_time + INTERVAL '26 minutes'),
    (room_id, user2_id, 'how do you handle the collaborative editing part?', base_time + INTERVAL '26 minutes 45 seconds'),
    (room_id, user1_id, 'we''re using CRDTs', base_time + INTERVAL '27 minutes'),
    (room_id, user1_id, 'Conflict-free Replicated Data Types', base_time + INTERVAL '27 minutes 20 seconds'),
    (room_id, user2_id, 'oh yeah I''ve heard of those', base_time + INTERVAL '28 minutes'),
    (room_id, user2_id, 'never actually implemented one though', base_time + INTERVAL '28 minutes 30 seconds'),
    (room_id, user1_id, 'they''re pretty mind-bending at first', base_time + INTERVAL '29 minutes'),
    (room_id, user1_id, 'but they solve the conflict resolution problem elegantly', base_time + INTERVAL '29 minutes 45 seconds'),
    (room_id, user2_id, 'I should look into that', base_time + INTERVAL '30 minutes'),
    (room_id, user2_id, 'sounds useful for what I might need in the future', base_time + INTERVAL '30 minutes 30 seconds'),
    (room_id, user1_id, 'definitely worth learning', base_time + INTERVAL '31 minutes'),
    (room_id, user1_id, 'there are some good libraries out there now', base_time + INTERVAL '31 minutes 30 seconds'),
    (room_id, user1_id, 'Yjs is a popular one', base_time + INTERVAL '32 minutes'),
    (room_id, user2_id, 'I''ll check it out, thanks!', base_time + INTERVAL '32 minutes 45 seconds'),
    (room_id, user2_id, 'changing topics a bit... have you been following the AI stuff lately?', base_time + INTERVAL '33 minutes'),
    (room_id, user1_id, 'oh man, it''s impossible not to', base_time + INTERVAL '34 minutes'),
    (room_id, user1_id, 'feels like something new drops every week', base_time + INTERVAL '34 minutes 30 seconds'),
    (room_id, user2_id, 'right?? it''s wild', base_time + INTERVAL '35 minutes'),
    (room_id, user2_id, 'I''ve been experimenting with LLMs for code generation', base_time + INTERVAL '35 minutes 45 seconds'),
    (room_id, user1_id, 'how''s that going?', base_time + INTERVAL '36 minutes'),
    (room_id, user2_id, 'honestly pretty well', base_time + INTERVAL '36 minutes 30 seconds'),
    (room_id, user2_id, 'speeds up boilerplate stuff significantly', base_time + INTERVAL '37 minutes'),
    (room_id, user1_id, 'yeah I use it for that too', base_time + INTERVAL '37 minutes 45 seconds'),
    (room_id, user1_id, 'also helps with writing tests', base_time + INTERVAL '38 minutes'),
    (room_id, user2_id, 'oh that''s a good use case', base_time + INTERVAL '38 minutes 30 seconds'),
    (room_id, user2_id, 'I hate writing tests lol', base_time + INTERVAL '39 minutes'),
    (room_id, user1_id, 'who doesn''t? 😅', base_time + INTERVAL '39 minutes 30 seconds'),
    (room_id, user1_id, 'but future you will thank present you', base_time + INTERVAL '40 minutes'),
    (room_id, user2_id, 'true true', base_time + INTERVAL '40 minutes 45 seconds'),
    (room_id, user2_id, 'do you do TDD?', base_time + INTERVAL '41 minutes'),
    (room_id, user1_id, 'I try to', base_time + INTERVAL '41 minutes 30 seconds'),
    (room_id, user1_id, 'doesn''t always happen in reality though', base_time + INTERVAL '42 minutes'),
    (room_id, user2_id, 'same, it''s hard to maintain that discipline', base_time + INTERVAL '42 minutes 45 seconds'),
    (room_id, user1_id, 'especially when you''re in the flow', base_time + INTERVAL '43 minutes'),
    (room_id, user1_id, 'sometimes I just want to code and worry about tests later', base_time + INTERVAL '43 minutes 45 seconds'),
    (room_id, user2_id, 'exactly!', base_time + INTERVAL '44 minutes'),
    (room_id, user2_id, 'though "later" sometimes never comes...', base_time + INTERVAL '44 minutes 30 seconds'),
    (room_id, user1_id, 'haha guilty as charged', base_time + INTERVAL '45 minutes'),
    (room_id, user1_id, 'technical debt is real', base_time + INTERVAL '45 minutes 30 seconds'),
    (room_id, user2_id, 'oh don''t even get me started', base_time + INTERVAL '46 minutes'),
    (room_id, user2_id, 'we have so much tech debt in our codebase', base_time + INTERVAL '46 minutes 45 seconds'),
    (room_id, user1_id, 'every codebase does if we''re being honest', base_time + INTERVAL '47 minutes'),
    (room_id, user2_id, 'fair point', base_time + INTERVAL '47 minutes 30 seconds'),
    (room_id, user2_id, 'do you ever get time to refactor?', base_time + INTERVAL '48 minutes'),
    (room_id, user1_id, 'sometimes, if I can justify it to the PM', base_time + INTERVAL '48 minutes 45 seconds'),
    (room_id, user1_id, 'they usually want new features though', base_time + INTERVAL '49 minutes'),
    (room_id, user2_id, 'ugh yeah the eternal struggle', base_time + INTERVAL '49 minutes 45 seconds'),
    (room_id, user2_id, 'new features vs maintenance', base_time + INTERVAL '50 minutes'),
    (room_id, user1_id, 'I try to sneak in refactoring while working on features', base_time + INTERVAL '50 minutes 45 seconds'),
    (room_id, user1_id, 'the boy scout rule, you know?', base_time + INTERVAL '51 minutes'),
    (room_id, user2_id, 'leave the code better than you found it', base_time + INTERVAL '51 minutes 30 seconds'),
    (room_id, user2_id, 'yeah that''s a good philosophy', base_time + INTERVAL '52 minutes'),
    (room_id, user1_id, 'it adds up over time', base_time + INTERVAL '52 minutes 45 seconds'),
    (room_id, user2_id, 'hey random question', base_time + INTERVAL '53 minutes'),
    (room_id, user2_id, 'what''s your dev setup like?', base_time + INTERVAL '53 minutes 30 seconds'),
    (room_id, user1_id, 'ooh good question', base_time + INTERVAL '54 minutes'),
    (room_id, user1_id, 'I''m a VS Code person', base_time + INTERVAL '54 minutes 30 seconds'),
    (room_id, user1_id, 'with a ton of extensions', base_time + INTERVAL '55 minutes'),
    (room_id, user2_id, 'nice, me too!', base_time + INTERVAL '55 minutes 30 seconds'),
    (room_id, user2_id, 'what extensions do you use?', base_time + INTERVAL '56 minutes'),
    (room_id, user1_id, 'the usual suspects - Prettier, ESLint', base_time + INTERVAL '56 minutes 45 seconds'),
    (room_id, user1_id, 'GitLens is a must-have', base_time + INTERVAL '57 minutes'),
    (room_id, user1_id, 'and I really like Error Lens', base_time + INTERVAL '57 minutes 30 seconds'),
    (room_id, user2_id, 'Error Lens is amazing', base_time + INTERVAL '58 minutes'),
    (room_id, user2_id, 'seeing errors inline is so helpful', base_time + INTERVAL '58 minutes 30 seconds'),
    (room_id, user1_id, 'right? game changer', base_time + INTERVAL '59 minutes'),
    (room_id, user1_id, 'I also use Vim keybindings', base_time + INTERVAL '59 minutes 45 seconds'),
    (room_id, user2_id, 'oh you''re one of those people 😄', base_time + INTERVAL '60 minutes'),
    (room_id, user1_id, 'haha what can I say', base_time + INTERVAL '60 minutes 30 seconds'),
    (room_id, user1_id, 'once you go Vim, you can''t go back', base_time + INTERVAL '61 minutes'),
    (room_id, user2_id, 'I tried learning it once', base_time + INTERVAL '61 minutes 45 seconds'),
    (room_id, user2_id, 'gave up after a week', base_time + INTERVAL '62 minutes'),
    (room_id, user1_id, 'lol it''s definitely a commitment', base_time + INTERVAL '62 minutes 30 seconds'),
    (room_id, user1_id, 'but the productivity boost is worth it', base_time + INTERVAL '63 minutes'),
    (room_id, user2_id, 'maybe I''ll try again someday', base_time + INTERVAL '63 minutes 45 seconds'),
    (room_id, user2_id, 'what about terminal? what do you use?', base_time + INTERVAL '64 minutes'),
    (room_id, user1_id, 'Warp actually', base_time + INTERVAL '64 minutes 30 seconds'),
    (room_id, user1_id, 'switched from iTerm2 a few months ago', base_time + INTERVAL '65 minutes'),
    (room_id, user2_id, 'oh I''ve been curious about Warp', base_time + INTERVAL '65 minutes 45 seconds'),
    (room_id, user2_id, 'is it worth the switch?', base_time + INTERVAL '66 minutes'),
    (room_id, user1_id, 'I think so', base_time + INTERVAL '66 minutes 30 seconds'),
    (room_id, user1_id, 'the command palette is really nice', base_time + INTERVAL '67 minutes'),
    (room_id, user1_id, 'and the AI command search is helpful', base_time + INTERVAL '67 minutes 45 seconds'),
    (room_id, user2_id, 'hmm I might check it out', base_time + INTERVAL '68 minutes'),
    (room_id, user1_id, 'you should!', base_time + INTERVAL '68 minutes 30 seconds'),
    (room_id, user1_id, 'anyway, what are you working on this week?', base_time + INTERVAL '69 minutes'),
    (room_id, user2_id, 'got a big feature deadline coming up', base_time + INTERVAL '70 minutes'),
    (room_id, user2_id, 'building out a dashboard for analytics', base_time + INTERVAL '70 minutes 45 seconds'),
    (room_id, user1_id, 'nice! what library for charts?', base_time + INTERVAL '71 minutes'),
    (room_id, user2_id, 'using Recharts', base_time + INTERVAL '71 minutes 30 seconds'),
    (room_id, user2_id, 'it integrates well with React', base_time + INTERVAL '72 minutes'),
    (room_id, user1_id, 'yeah Recharts is solid', base_time + INTERVAL '72 minutes 45 seconds'),
    (room_id, user1_id, 'have you looked at Chart.js or D3?', base_time + INTERVAL '73 minutes'),
    (room_id, user2_id, 'D3 seems too complex for what I need', base_time + INTERVAL '74 minutes'),
    (room_id, user2_id, 'and Chart.js felt less React-y', base_time + INTERVAL '74 minutes 30 seconds'),
    (room_id, user1_id, 'that''s fair', base_time + INTERVAL '75 minutes'),
    (room_id, user1_id, 'Recharts is probably the sweet spot', base_time + INTERVAL '75 minutes 30 seconds'),
    (room_id, user2_id, 'that''s what I figured', base_time + INTERVAL '76 minutes'),
    (room_id, user2_id, 'the API is pretty intuitive too', base_time + INTERVAL '76 minutes 45 seconds'),
    (room_id, user1_id, 'definitely', base_time + INTERVAL '77 minutes'),
    (room_id, user1_id, 'when''s your deadline?', base_time + INTERVAL '77 minutes 30 seconds'),
    (room_id, user2_id, 'end of this week 😰', base_time + INTERVAL '78 minutes'),
    (room_id, user1_id, 'oh wow, that''s soon', base_time + INTERVAL '78 minutes 45 seconds'),
    (room_id, user1_id, 'you gonna make it?', base_time + INTERVAL '79 minutes'),
    (room_id, user2_id, 'I think so?', base_time + INTERVAL '79 minutes 45 seconds'),
    (room_id, user2_id, 'might need to pull a late night or two', base_time + INTERVAL '80 minutes'),
    (room_id, user1_id, 'been there, done that', base_time + INTERVAL '80 minutes 45 seconds'),
    (room_id, user1_id, 'make sure you take breaks though', base_time + INTERVAL '81 minutes'),
    (room_id, user2_id, 'yeah yeah I know', base_time + INTERVAL '81 minutes 45 seconds'),
    (room_id, user2_id, 'I''m bad at that honestly', base_time + INTERVAL '82 minutes'),
    (room_id, user1_id, 'same, I get too focused', base_time + INTERVAL '82 minutes 45 seconds'),
    (room_id, user1_id, 'then I look up and it''s been 4 hours', base_time + INTERVAL '83 minutes'),
    (room_id, user2_id, 'lol exactly!', base_time + INTERVAL '83 minutes 45 seconds'),
    (room_id, user2_id, 'and my back is killing me', base_time + INTERVAL '84 minutes'),
    (room_id, user1_id, 'oh man, ergonomics is important', base_time + INTERVAL '84 minutes 45 seconds'),
    (room_id, user1_id, 'I got a standing desk last year', base_time + INTERVAL '85 minutes'),
    (room_id, user2_id, 'worth it?', base_time + INTERVAL '85 minutes 30 seconds'),
    (room_id, user1_id, 'absolutely', base_time + INTERVAL '86 minutes'),
    (room_id, user1_id, 'my back pain went away', base_time + INTERVAL '86 minutes 30 seconds'),
    (room_id, user2_id, 'I should probably get one', base_time + INTERVAL '87 minutes'),
    (room_id, user2_id, 'any recommendations?', base_time + INTERVAL '87 minutes 45 seconds'),
    (room_id, user1_id, 'I got the Uplift V2', base_time + INTERVAL '88 minutes'),
    (room_id, user1_id, 'it''s pricey but solid quality', base_time + INTERVAL '88 minutes 45 seconds'),
    (room_id, user2_id, 'I''ll look into it, thanks!', base_time + INTERVAL '89 minutes'),
    (room_id, user1_id, 'also get a good chair', base_time + INTERVAL '89 minutes 45 seconds'),
    (room_id, user1_id, 'that''s even more important', base_time + INTERVAL '90 minutes'),
    (room_id, user2_id, 'yeah I have a Herman Miller', base_time + INTERVAL '90 minutes 45 seconds'),
    (room_id, user2_id, 'that was my pandemic splurge', base_time + INTERVAL '91 minutes'),
    (room_id, user1_id, 'nice! those are amazing', base_time + INTERVAL '91 minutes 45 seconds'),
    (room_id, user1_id, 'I have an Aeron', base_time + INTERVAL '92 minutes'),
    (room_id, user2_id, 'same! Aeron crew', base_time + INTERVAL '92 minutes 30 seconds'),
    (room_id, user1_id, 'best chair ever made imo', base_time + INTERVAL '93 minutes'),
    (room_id, user2_id, 'agreed', base_time + INTERVAL '93 minutes 45 seconds'),
    (room_id, user2_id, 'okay I should probably get back to work', base_time + INTERVAL '94 minutes'),
    (room_id, user2_id, 'this dashboard isn''t gonna build itself', base_time + INTERVAL '94 minutes 45 seconds'),
    (room_id, user1_id, 'haha fair enough', base_time + INTERVAL '95 minutes'),
    (room_id, user1_id, 'good luck with the deadline!', base_time + INTERVAL '95 minutes 30 seconds'),
    (room_id, user2_id, 'thanks! good luck with your collab platform', base_time + INTERVAL '96 minutes'),
    (room_id, user1_id, 'thanks! catch you later', base_time + INTERVAL '96 minutes 45 seconds'),
    (room_id, user2_id, 'later!', base_time + INTERVAL '97 minutes'),
    
    -- Short break in conversation
    
    (room_id, user2_id, 'hey quick question', base_time + INTERVAL '120 minutes'),
    (room_id, user1_id, 'shoot', base_time + INTERVAL '121 minutes'),
    (room_id, user2_id, 'what''s the best way to handle API errors in React?', base_time + INTERVAL '122 minutes'),
    (room_id, user1_id, 'I usually use Error Boundaries', base_time + INTERVAL '123 minutes'),
    (room_id, user1_id, 'and display toast notifications for user-facing errors', base_time + INTERVAL '123 minutes 45 seconds'),
    (room_id, user2_id, 'what do you use for toasts?', base_time + INTERVAL '124 minutes'),
    (room_id, user1_id, 'react-hot-toast is nice', base_time + INTERVAL '125 minutes'),
    (room_id, user1_id, 'very simple API', base_time + INTERVAL '125 minutes 30 seconds'),
    (room_id, user2_id, 'cool I''ll check it out', base_time + INTERVAL '126 minutes'),
    (room_id, user2_id, 'thanks!', base_time + INTERVAL '126 minutes 30 seconds'),
    (room_id, user1_id, 'np!', base_time + INTERVAL '127 minutes'),
    
    -- Another break
    
    (room_id, user1_id, 'how''s it going?', base_time + INTERVAL '150 minutes'),
    (room_id, user2_id, 'making progress!', base_time + INTERVAL '151 minutes'),
    (room_id, user2_id, 'got most of the charts working', base_time + INTERVAL '151 minutes 45 seconds'),
    (room_id, user1_id, 'awesome!', base_time + INTERVAL '152 minutes'),
    (room_id, user2_id, 'just need to add some interactivity', base_time + INTERVAL '153 minutes'),
    (room_id, user1_id, 'like tooltips and stuff?', base_time + INTERVAL '154 minutes'),
    (room_id, user2_id, 'yeah, and drill-downs', base_time + INTERVAL '155 minutes'),
    (room_id, user1_id, 'nice, sounds like you''re on track', base_time + INTERVAL '156 minutes'),
    (room_id, user2_id, 'fingers crossed 🤞', base_time + INTERVAL '157 minutes'),
    (room_id, user1_id, 'you got this!', base_time + INTERVAL '158 minutes');
END $$;